shoes/demo/urls.py
from django.urls import path
from . import views

app_name='demo'
urlpatterns = [
    path('',views.get,name='get'),
    path('updateusershoes',views.updateusershoes,name='updateusershoes'),
    path('<id>/getusershoes',views.getusershoes,name='getusershoes'),
]

shoes/shoes/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('demo.urls')),
]

shoes/demo/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    name=models.CharField(max_length=20)
    phone=models.CharField(max_length=11)
    def __str__(self):
        return self.name


class Shoes(models.Model):
    color=models.CharField(max_length=20)
    size=models.CharField(max_length=11)
    u=models.ForeignKey(to=User,on_delete=models.CASCADE)

shoes/demo/forms.py
from django import forms
from .models import Shoes,User


class Userform(forms.ModelForm):
    class Meta:
        model=User
        fields='__all__'

class Shoesform(forms.ModelForm):
    class Meta:
        model=Shoes
        fields='__all__'

shoes/demo/views.py
from django.shortcuts import render,HttpResponse,reverse
from django.http import JsonResponse
from .models import User,Shoes
from .forms import Shoesform,Userform

# Create your views here.
def get(request):
    user=User.objects.all()
    return render(request,'demo/get.html',{'user':user})

def updateusershoes(request):
    if request.method=='GET':
        shoes = Shoesform()
        return render(request,'demo/post.html',{'shoes':shoes})
    else:
        newshoes=Shoesform(request.POST)
        uid=''
        if newshoes.is_valid():
        #     newshoes.save()
            uid = newshoes.cleaned_data['u'].id
        user = User.objects.filter(id=uid).first()
        shoes = Shoes.objects.filter(u=user)
        shoesid = []
        for item in shoes:
            shoesid.append(str(item.id))
        return JsonResponse({'success':True,'message':'OK','result':{'userid':uid,'shoesid':shoesid}})


def getusershoes(request,id):
    user=User.objects.filter(id=id).first()
    shoes=Shoes.objects.filter(u=user)
    shoesarr=[]
    for item in shoes:
        shoe={'id':item.id,"size":item.size,"color":item.color}
        shoesarr.append(shoe)
    return JsonResponse({"username":shoes[0].u.name,"shoes":shoesarr})

shoes/demo/templates/demo/get.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>


    {% for item in user %}
        <a href="{% url 'demo:getusershoes' item.id %}">{{ item.name }}</a>
    {% endfor %}

    <br>

<a href="{% url 'demo:updateusershoes' %}">添加鞋子</a>




</body>
</html>

shoes/demo/templates/demo/post.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<form action="updateusershoes" method="post">
    {% csrf_token | safe %}
    {{ shoes }}
    <button type="submit">添加</button>
</form>
</body>
</html>